# Generated by Django 6.0.3 on 2026-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта онлайн'), ('cash', 'Наличными при получении'), ('card_on_delivery', 'Картой при получении')], max_length=50, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('post', 'Почта')], max_length=50, verbose_name='Shipping method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
